src/website/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('website_api.urls', namespace='website_api')),
    path('', include('website_api.urls', namespace='website_api')),

]

src/website_api/urls.py
import django
from django.contrib.auth import views as auth_views

from django.urls import path

from website_api import views

app_name = 'website_web'

urlpatterns = [
    path('list-articles', views.list_articles, name='article_list'),
    path('oauth/facebook', views.facebook_oauth, name='facebook_oauth'),
    path('get-articles', views.get_articles, name='article_get'),
    path('add-articles', views.add_articles, name='article_add'),
    path('auth/login', auth_views.LoginView.as_view(), name='login_page'),
    # path('', views.home_page, name='home_page'),
]

src/website_api/models.py
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from django.template.defaultfilters import slugify


class Article(models.Model):
    title = models.CharField(max_length=500)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    content = models.CharField(max_length=2500)
    slug = models.SlugField(unique=True, blank=True)

    def __str__(self):
        return self.title


@receiver(models.signals.pre_save, sender=Article)
def set_slug(sender, instance, **c):
    if not instance.slug:
        instance.slug = slugify(instance.title)

src/website_api/views.py
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.shortcuts import render, redirect
from django.utils.crypto import get_random_string


from website_api.models import Article


def list_articles(request):
    state = get_random_string(32)
    print(request.user.id)
    cache.set(state, request.user.id, 6000)
    return render(request,'list-articles.html')


def get_articles(request, my_slug):
    article = Article.objects.get(slug=my_slug)
    return render(request,'get-articles.html', {'article': article})


@login_required()
def add_articles(request):
    title = ''
    content = ''
    error = False

    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']

        if len(title) > 30:
            error = True
        else:
            author = request.user.detail[0].bio
            article = Article.objects.create(title=title, content=content, author=author)
            return redirect('website_web:article_get', article.slug)
    return render(request, 'add-articles.html', {'title': title, 'content': content, 'error': error})


def facebook_oauth(request):

    state=request.Get['state']
    grant=request.Get['code']
    user_id=cache.request.id
    client_id = ''
    client_secret = ''
    redirect_uri = 'http://127.0.0.1/api/articles'

    data = {'client_id': client_id, 'redirect_uri': redirect_uri,
            'client_secret': client_secret, 'code': grant}
    res= request.get('https://graph.facebook.com/v2.12/oauth/access_token',params=data).json()
    print(res)
    access_token = res['access_token']


def home_page(request):
    return render(request,'main.html')

src/website_api/templates/add-articles.html
{% extends 'main.html' %}


{% block page_content %}
    {% if error %}
        <span style="color: red">Please fix error and resubmit</span>
    {% endif %}
    <div></div>
    <form method="post" action="{% url 'website_api:article_add' %}">
        {% csrf_token %}
        <input name="title" placeholder="title" value="{{ title }}">
        <textarea name="content" placeholder="write something...">{{ content }}</textarea>
        <button type="submit">Submit</button>
    </form>
{% endblock %}

{% block page_title %}
    <title>Add New Article</title>
{% endblock %}

src/website_api/templates/get-articles.html
{% extends 'main.html' %}


{% block page_content %}
        <h1>{{ article.title }}</h1>
        <span>{{ article.author.first_name }}</span>
        <span>{{ article.created_at | date:"Y d" }}</span>

        <div>{{ article.content }}</div>
{% endblock %}

{% block page_title %}
    <title>{{ article.title }}</title>
    <meta property="og:title" content="{{ article.title }}">
{% endblock %}

src/website_api/templates/list-articles.html
{% extends 'main.html' %}


{% block page_content %}
    <a href="https://www.facebook.com/v2.12/dialog/oauth?client_id=173482556629782&scope=publish_actions&redirect_uri=http://localhost:8080/oauth/facebook&state={{ state }}">Connect Your FB</a>
    <form action="{% url 'website_api:article_list' %}" method="get">
        <input name="q" placeholder="type keywords.." value="{{ query }}">
        <button type="submit">Search</button>
    </form>
    <a href="{% url 'website_api:article_add' %}">add new article</a>
    <ul>
        {% for article in my_articles %}
            <li><a href="{% url 'website_api:article_get' article.slug %}">{{ article.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}


{% block page_title %}
    <title>All articles</title>
{% endblock %}

src/website_api/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block page_title %}
        <title>My Main layout</title>
    {% endblock %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">My Website</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'website_api:article_list' %}">Articles</a>
            </li>
           <li class="nav-item">
                <a class="nav-link" href="{% url 'website_web:login_page' %}">Login</a>
            </li>

        </ul>
    </div>
</nav>

{% block page_content %}
    hello world!
{% endblock %}
</body>
</html>